django_docker/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', TemplateView.as_view(template_name="index.html"), name='home'),
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
)

polls/urls.py
from django.conf.urls import patterns, url

from . import views

urlpatterns = patterns('',
    # ex: /polls/
    url(r'^$', views.index, name='index'),
    # ex: /polls/5/
    url(r'^(?P<poll_id>\d+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<poll_id>\d+)/results/$', views.results, name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<poll_id>\d+)/vote/$', views.vote, name='vote'),
)

polls/models.py
from django.db import models
from django.utils import timezone
import datetime

class Poll(models.Model):
    question = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __unicode__(self):
        return self.question

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <  now

class Choice(models.Model):
    poll = models.ForeignKey(Poll)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __unicode__(self):
        return self.choice_text

polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext, loader
from django.core.urlresolvers import reverse
from django.shortcuts import render, get_object_or_404

from .models import Choice, Poll

def index(request):
    latest_poll_list = Poll.objects.all().order_by('-pub_date')[:5]
    context = {'latest_poll_list': latest_poll_list}
    print context
    for a in latest_poll_list:
        print a.id
    return render(request, 'polls/index.html', context)

def detail(request, poll_id):
    poll = get_object_or_404(Poll, pk=poll_id)
    return render(request, 'polls/detail.html', {'poll': poll})

def results(request, poll_id):
    poll = get_object_or_404(Poll, pk=poll_id)
    return render(request, 'polls/results.html', {'poll': poll})

def vote(request, poll_id):
    p = get_object_or_404(Poll, pk=poll_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the poll voting form.
        return render(request, 'polls/detail.html', {
            'poll': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))

polls/templates/polls/detail.html
{% extends 'base.html' %}

{% block breadcrumb-page %}{{ poll.question }}{% endblock breadcrumb-page %}

{% block content %}
    <h1>{{ poll.question }}?</h1>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'polls:vote' poll.id %}" method="post" class="form-horizontal">
    {% csrf_token %}
    {% for choice in poll.choice_set.all %}
         <div class="control-group">
            <label class="control-label" for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
             <div class="controls">
                 <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
             </div>
        </div>
    {% endfor %}
    <div class="control-group">
        <div class="controls">
            <input type="submit" value="Vote" />
        </div>
    </div>
    </form>
{% endblock content %}

polls/templates/polls/index.html
{% extends 'base.html' %}

{% block breadcrumb-page %}list{% endblock breadcrumb-page %}

{% block content %}
    <h1>Polls</h1>
    {% if latest_poll_list %}
        <ul>
        {% for poll in latest_poll_list %}
            <li><a href="{% url 'polls:detail' poll.pk %}">{{ poll.question }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
{% endblock content %}

polls/templates/polls/results.html
{% extends 'base.html' %}

{% block breadcrumb-page %}{{ poll.question }} Results{% endblock breadcrumb-page %}

{% block content %}
    <h1>{{ poll.question }}</h1>

    <ul>
    {% for choice in poll.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
    </ul>

    <a href="{% url 'polls:detail' poll.id %}">Vote again?</a>

{% endblock content %}

templates/base.html
{% load static from staticfiles %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <!-- [if it IE]> <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> <![endif]-->
    <title>
        {% block title %}{% endblock title %} | Django + Docker Example
    </title>

    {% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap-custom.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/main.css" %}"> {% endblock stylesheets %}
    {% block page_styles %}{% endblock page_styles %}
    {% block js %}
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js" ></script>
    <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
    {% endblock js %} {% block page_js %}{% endblock page_js %}
</head>
<body>

<!-- navigation -->
<div class="navbar navbar-static-top">
    <div class="navbar-inner navbar-fixed-top ">
        <div class="container" >
            <div class="brand logo"><img src='{% static "img/docker-top-logo.png" %}' /> </div>
            <ul class="nav pull-right">
                <li class="active"><a href="{% url 'polls:index' %}">Polls</a></li>
                <li><a href="http://www.docker.io/">Docker project</a></li>
            </ul>
        </div>
    </div>
</div>

{% block breadcrumbs %}
<ul class="breadcrumb">
  <li><a href="{% url 'home' %}">Home</a> <span class="divider">/</span></li>
  <li><a href="{% url 'polls:index' %}">Polls</a> <span class="divider">/</span></li>
  {% block breadcrumb-page %}{% endblock breadcrumb-page %}
</ul>
{% endblock breadcrumbs %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="span9 offset2 box">
        {% block content %}
            <h1>Example App</h1>
        {% endblock content %}

        </div>
    </div>
</div>
{% endblock body %}

</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static from staticfiles %}

{% block breadcrumbs %}
{% endblock breadcrumbs %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="box">

<div class="hero-unit">
  <h1>Django + Docker</h1>
  <p>A match made in heaven</p>
  <p>DjangoCon 2013 Rules!</p>
  <p>
    <a class="btn btn-primary btn-large" href='{% url 'polls:index' %}'>Polls App</a>
  </p>
</div>

     <!-- Example row of columns -->
      <div class="row">
        <div class="span5">
          <p><img src='{% static "img/django-pony.png" %}' /></p>
        </div>
        <div class="span5">
          <p><img src='{% static "img/docker-logo.png" %}' /></p>
        </div>
      </div>

        </div>
    </div>
</div>
{% endblock body %}